FROM nvidia/cuda:11.7.1-base-ubuntu20.04

RUN apt update && \
    apt install -y git wget dumb-init && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py38_4.12.0-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p $CONDA_DIR && \
    rm ~/miniconda.sh

ENV PATH ${CONDA_DIR}/bin:${PATH}

RUN conda install -y jupyterlab
RUN pip install torch torchvision --index-url https://download.pytorch.org/whl/cu117
RUN pip install pandas pyarrow numpy transformers clickhouse-driver

ENTRYPOINT ["jupyterlab", "--ip", "0.0.0.0", "--no-browser", "--allow-root"]
