#!/bin/sh
echo "*** $(date -R) ***" | logger
echo "Starting ntpdate..." | logger
/usr/sbin/ntpdate -s -b -u 0.gentoo.pool.ntp.org 1.gentoo.pool.ntp.org 2.gentoo.pool.ntp.org 3.gentoo.pool.ntp.org | logger
